// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ProsumerInfo.Data;

namespace ProsumerInfo.Migrations
{
    [DbContext(typeof(ProsumerInfoContext))]
    [Migration("20180519212109_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProsumerInfo.Models.Prosumer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PublicKey");

                    b.Property<int?>("SmartMeterId");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("SmartMeterId");

                    b.ToTable("Prosumers");
                });

            modelBuilder.Entity("ProsumerInfo.Models.SmartMeter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GeneratedPower");

                    b.Property<int>("UsedPower");

                    b.HasKey("Id");

                    b.ToTable("SmartMeters");
                });

            modelBuilder.Entity("ProsumerInfo.Models.Prosumer", b =>
                {
                    b.HasOne("ProsumerInfo.Models.SmartMeter", "SmartMeter")
                        .WithMany()
                        .HasForeignKey("SmartMeterId");
                });
#pragma warning restore 612, 618
        }
    }
}
